import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
// import { serif } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "./favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} text-[#646464] bg-zinc-100 dark:bg-zinc-950 dark:text-zinc-400 p-2 pb-16`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
